# Generated by Django 5.2.7 on 2025-10-03 13:09

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Expense',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('merchant', models.CharField(max_length=100)),
                ('transaction_date', models.DateTimeField()),
                ('payment_mode', models.CharField(choices=[('UPI', 'UPI'), ('CARD', 'Card'), ('CASH', 'Cash')], max_length=10)),
                ('category', models.CharField(choices=[('food', 'Food & Dining'), ('transport', 'Transportation'), ('bills', 'Utilities & Bills'), ('entertainment', 'Entertainment'), ('shopping', 'Shopping'), ('education', 'Education')], max_length=20)),
                ('transaction_type', models.CharField(choices=[('debit', 'Debit'), ('credit', 'Credit')], max_length=10)),
                ('description', models.TextField(blank=True, null=True)),
            ],
        ),
    ]
